export const GET_TEST_SESSION = 'GET_TEST_SESSION';
export const SET_VIDEO_RATING = 'SET_VIDEO_RATING';
export const TEST_SESSION_ERROR = 'TEST_SESSION_ERROR';
export const CLEAR_TEST_SESSION = 'CLEAR_TEST_SESSION';


export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
