export const GET_TEST_SESSION = 'GET_TEST_SESSION';
export const SET_VIDEO_RATING = 'SET_VIDEO_RATING';
export const TEST_SESSION_ERROR = 'TEST_SESSION_ERROR';
export const CLEAR_TEST_SESSION = 'CLEAR_TEST_SESSION';
export const SET_DATASET_NAME = 'SET_DATASET_NAME';
export const MARK_INSTRUCTION_PLAYED = 'MARK_INSTRUCTION_PLAYED';
export const ADD_SUBJECT_TO_TEST_SESSION = 'ADD_SUBJECT_TO_TEST_SESSION';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_ALL_EXPERIMENT_RESULTS = 'GET_ALL_EXPERIMENT_RESULTS';
export const EXPERIMENT_RESULT_ERROR = 'EXPERIMENT_RESULT_ERROR';
export const ADD_SUBJECT_TO_EXPERIMENT_RESULT = 'ADD_SUBJECT_TO_EXPERIMENT_RESULT';
export const ADD_CHARACTERISTIC_TO_SUBJECT_IN_EXPERIMENT_RESULT = 'ADD_CHARACTERISTIC_TO_SUBJECT_IN_EXPERIMENT_RESULT';
